"""Added creator_id to review

Revision ID: 14c3d80dba13
Revises: c8d16d7cbd09
Create Date: 2021-11-25 09:37:06.957665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c3d80dba13'
down_revision = 'c8d16d7cbd09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'flasklogin-users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'creator_id')
    # ### end Alembic commands ###
