"""Initial migration

Revision ID: 34310442cb3d
Revises: 
Create Date: 2021-11-18 14:23:52.879764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34310442cb3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flasklogin-users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('review_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('review_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('flasklogin-users')
    # ### end Alembic commands ###
